language: objective-c
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/TravisExample_Ad_Hoc.mobileprovision.enc -d -a -out scripts/profile/TravisExample_Ad_Hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
- ./scripts/update-bundle.sh
script:
- xcodebuild -project DemoProjectTravis.xcodeproj -target DemoProjectTravis -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
- xcodebuild test -project DemoProjectTravis.xcodeproj  -scheme
  DemoProjectTravis  -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh

env:
  global:
  - secure: g5x+iCGZXGPhUYiET1hePmRV1ie9psWwJ6SO0yIDxYfGk1OJlwza7jHDU2WqoeXcC0xUISBQiQ2Nyui4YbR4eIQa3pB4pDRYDNs4RlwePn4GGM64sq9LtbS9Q+hoZYHXUeQj15ENfYp6z7n1Aq/n6/Uz0xKzkQccul4JX//y9/o=
  - APP_NAME="DemoProjectTravis"
  - 'DEVELOPER_NAME="iPhone Distribution: {your_name} ({code})"'
  - PROFILE_NAME="TravisExample_Ad_Hoc"
  - secure: OnMQqAti6m7/x/hEytc0ZD9v3/2MI7WQCidwEixpfM0Iz0Rm5S4eK7tZn3bgIQtddz5KU5ZxKXHFO6Hrtp1sAuTbz6mJcBQRoY1yCckKSFHWKi6CqZ8WNziP8803kHY89mjHcRadR/SOrVj1r2xho+Rp8fIVQ5h2OysXoSxGYXA=